language: go

go:
  - 1.4
  - tip

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-4.8
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq gcc-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="gcc-4.8" CC="gcc-4.8"; fi
